# Generated by Django 5.2.4 on 2025-07-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('sector_retail', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('contacto_principal', models.CharField(max_length=200)),
                ('correo_principal', models.EmailField(max_length=254)),
                ('celular_principal', models.CharField(max_length=20)),
                ('contacto_alterno', models.CharField(blank=True, max_length=200)),
                ('correo_alterno', models.EmailField(blank=True, max_length=254)),
                ('celular_alterno', models.CharField(blank=True, max_length=20)),
                ('ejecutivo_lockton', models.CharField(max_length=200)),
                ('correo_ejecutivo', models.EmailField(max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
